In [1]:
import numpy as np 
import torch 
torch.manual_seed(1)
print(torch.__version__)

1.6.0


In [3]:
x = torch.Tensor(2,2)
x

tensor([[4.6837e-39, 5.9694e-39],
        [8.9082e-39, 1.0194e-38]])

In [4]:
x.type(), x.size(), x.numel()

('torch.FloatTensor', torch.Size([2, 2]), 4)

In [8]:
x2 = torch.Tensor(4,3,2,1)
x2

tensor([[[[1.0561e-38],
          [1.0653e-38]],

         [[4.1327e-39],
          [8.9082e-39]],

         [[9.8265e-39],
          [9.4592e-39]]],


        [[[1.0561e-38],
          [9.7347e-39]],

         [[9.1837e-39],
          [8.4490e-39]],

         [[1.0286e-38],
          [8.4490e-39]]],


        [[[9.2755e-39],
          [8.9082e-39]],

         [[1.0653e-38],
          [1.0469e-38]],

         [[1.0102e-38],
          [8.4490e-39]]],


        [[[8.7245e-39],
          [1.0102e-38]],

         [[1.0653e-38],
          [8.7245e-39]],

         [[1.0286e-38],
          [1.6956e-43]]]])

In [10]:
x2.type(), x2.size(), x2.numel()

('torch.FloatTensor', torch.Size([4, 3, 2, 1]), 24)

In [11]:
torch.zeros(4,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [12]:
torch.ones(4,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
torch.eye(4,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [14]:
torch.rand(4,4)

tensor([[0.7576, 0.2793, 0.4031, 0.7347],
        [0.0293, 0.7999, 0.3971, 0.7544],
        [0.5695, 0.4388, 0.6387, 0.5247],
        [0.6826, 0.3051, 0.4635, 0.4550]])

In [15]:
torch.randn(4,4)

tensor([[-0.6970, -1.1608,  0.6995,  0.1991],
        [ 0.8657,  0.2444, -0.6629,  0.8073],
        [ 1.1017, -0.1759, -2.2456, -1.4465],
        [ 0.0612, -0.6177, -0.7981, -0.1316]])

In [17]:
x3 = torch.arange(0,3,0.3)
x3

tensor([0.0000, 0.3000, 0.6000, 0.9000, 1.2000, 1.5000, 1.8000, 2.1000, 2.4000,
        2.7000])

In [19]:
torch.Tensor([[6,2],[3,4],[5,6]])

tensor([[6., 2.],
        [3., 4.],
        [5., 6.]])

In [21]:
numpy_test = np.array([[5,6],[10,11]])
torch.from_numpy(numpy_test)

tensor([[ 5,  6],
        [10, 11]], dtype=torch.int32)

In [22]:
x4 = torch.Tensor([[1,2,3],[4,5,6],[7,8,9]])
x4

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [23]:
x4[0:2,:]

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [24]:
x4[0:1,:] = torch.Tensor([62,72,80])
x4

tensor([[62., 72., 80.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]])

In [25]:
x4[1] = torch.Tensor([200,78,89])
x4

tensor([[ 62.,  72.,  80.],
        [200.,  78.,  89.],
        [  7.,   8.,   9.]])

In [28]:
x5 = torch.split(x4, split_size_or_sections=1,dim=0)
x5

(tensor([[62., 72., 80.]]),
 tensor([[200.,  78.,  89.]]),
 tensor([[7., 8., 9.]]))

In [29]:
torch.cat(x5, dim=1)

tensor([[ 62.,  72.,  80., 200.,  78.,  89.,   7.,   8.,   9.]])

In [33]:
tmp = torch.stack(x5, dim=1)
tmp

tensor([[[ 62.,  72.,  80.],
         [200.,  78.,  89.],
         [  7.,   8.,   9.]]])

In [35]:
tmp.size()

torch.Size([1, 3, 3])

In [36]:
x6 = torch.randn(3,3)
mask = torch.ByteTensor([[1,0,0],[1,1,1],[0,1,0]])
out = torch.masked_select(x6, mask)
out 

C:\Users\90553\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: masked_select received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (Triggered internally at  ..\aten\src\ATen\native\LegacyDefinitions.cpp:32.)
  This is separate from the ipykernel package so we can avoid doing imports until


tensor([-0.4212, -0.1232,  3.5870, -1.8313, -1.2770])

In [37]:
x7 = torch.zeros(2,2,1)
x7

tensor([[[0.],
         [0.]],

        [[0.],
         [0.]]])

In [38]:
x7.view(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [39]:
x7.view(-1)

tensor([0., 0., 0., 0.])

In [40]:
x8 = x7.squeeze()
x7,x8

(tensor([[[0.],
          [0.]],
 
         [[0.],
          [0.]]]), tensor([[0., 0.],
         [0., 0.]]))

In [41]:
x9 = torch.FloatTensor([[10,20,30],[40,50,60]])
x10 = torch.FloatTensor([[1,2,3],[4,5,6]])
x9,x10

(tensor([[10., 20., 30.],
         [40., 50., 60.]]), tensor([[1., 2., 3.],
         [4., 5., 6.]]))

In [42]:
x9 + x10, x9.add(x10), torch.add(x9,x10)

(tensor([[11., 22., 33.],
         [44., 55., 66.]]), tensor([[11., 22., 33.],
         [44., 55., 66.]]), tensor([[11., 22., 33.],
         [44., 55., 66.]]))

In [43]:
x10.sub(x9), x9.sub(x10)

(tensor([[ -9., -18., -27.],
         [-36., -45., -54.]]), tensor([[ 9., 18., 27.],
         [36., 45., 54.]]))

In [44]:
x9*x10, x9.mul(x10), torch.mul(x9,x10)

(tensor([[ 10.,  40.,  90.],
         [160., 250., 360.]]), tensor([[ 10.,  40.,  90.],
         [160., 250., 360.]]), tensor([[ 10.,  40.,  90.],
         [160., 250., 360.]]))

In [45]:
x9.pow(2), torch.pow(x9,2), x9**2

(tensor([[ 100.,  400.,  900.],
         [1600., 2500., 3600.]]), tensor([[ 100.,  400.,  900.],
         [1600., 2500., 3600.]]), tensor([[ 100.,  400.,  900.],
         [1600., 2500., 3600.]]))

In [46]:
x9.sqrt()

tensor([[3.1623, 4.4721, 5.4772],
        [6.3246, 7.0711, 7.7460]])

In [47]:
x10.log(), torch.log(x10)

(tensor([[0.0000, 0.6931, 1.0986],
         [1.3863, 1.6094, 1.7918]]), tensor([[0.0000, 0.6931, 1.0986],
         [1.3863, 1.6094, 1.7918]]))

In [48]:
x9 % 3, x9 / 3

(tensor([[1., 2., 0.],
         [1., 2., 0.]]), tensor([[ 3.3333,  6.6667, 10.0000],
         [13.3333, 16.6667, 20.0000]]))

In [50]:
x9,x10

(tensor([[10., 20., 30.],
         [40., 50., 60.]]), tensor([[1., 2., 3.],
         [4., 5., 6.]]))

In [51]:
x9.sum(), x9.max()

(tensor(210.), tensor(60.))

In [52]:
x10.min(), x10.min(0), x10.min(1)

(tensor(1.), torch.return_types.min(
 values=tensor([1., 2., 3.]),
 indices=tensor([0, 0, 0])), torch.return_types.min(
 values=tensor([1., 4.]),
 indices=tensor([0, 0])))

In [53]:
x10.max(1)

torch.return_types.max(
values=tensor([3., 6.]),
indices=tensor([2, 2]))

In [54]:
value, index = x10.max(1)
value, index

(tensor([3., 6.]), tensor([2, 2]))

In [55]:
x11 = torch.randn(3,5)
x12 = torch.randn(5,5)
x13 = torch.randn(5,3)
x11, x12, x13

(tensor([[-0.4791,  1.3790,  2.5286,  0.4107, -0.9880],
         [-0.9081,  0.5423,  0.1103, -2.2590,  0.6067],
         [-0.1383,  0.8310, -0.2477, -0.8029,  0.2366]]),
 tensor([[-0.5065,  0.0998, -0.6540,  0.7317, -1.4344],
         [-0.5008,  0.1716, -0.1600,  0.2546,  0.1938],
         [-2.5832,  0.8539,  1.2466,  0.5057,  0.9505],
         [ 1.2966,  0.8738,  0.3434, -1.0703, -0.8743],
         [-1.4648, -1.2629,  1.1220,  1.5663,  2.5581]]),
 tensor([[-1.1322, -0.0179,  0.1280],
         [-0.5552, -0.4575, -1.9599],
         [-1.1242, -1.5599,  1.4003],
         [ 0.2963, -1.0901, -0.2380],
         [ 0.6905,  0.4646, -0.7559]]))

In [56]:
torch.mm(x11,x12), x11.mm(x12)

(tensor([[-4.9999,  3.9548,  2.2772, -0.7079,  0.4714],
         [-3.9143, -2.6435,  0.5496,  2.8975,  5.0394],
         [-1.0939, -1.0831, -0.3615,  1.2151,  1.4312]]),
 tensor([[-4.9999,  3.9548,  2.2772, -0.7079,  0.4714],
         [-3.9143, -2.6435,  0.5496,  2.8975,  5.0394],
         [-1.0939, -1.0831, -0.3615,  1.2151,  1.4312]]))

In [57]:
x11.mm(x12).mm(x13)

tensor([[ 1.0210, -4.2816, -5.3899],
        [ 9.6202, -0.3951,  0.9506],
        [ 3.5947,  0.4194,  0.1054]])

In [59]:
x14 = torch.randn(3,4)
v = torch.randn(4)
x14, v

(tensor([[-2.0501,  0.6842, -0.8003, -0.3738],
         [ 1.4904, -1.2968, -0.3243,  0.3105],
         [-0.3423,  0.6976,  1.4117,  2.1331]]),
 tensor([-0.1602,  0.3615,  0.3725, -0.3054]))

In [60]:
torch.mv(x14,v), x14.mv(v)

(tensor([ 0.3919, -0.9233,  0.1815]), tensor([ 0.3919, -0.9233,  0.1815]))

In [61]:
x15 = torch.randn(10,3,4)
x16 = torch.randn(10,4,5)

torch.bmm(x15, x16).size()

torch.Size([10, 3, 5])

In [62]:
torch.bmm(x15, x16)

tensor([[[ 1.7138, -0.4345,  1.1420, -3.3325, -1.2142],
         [-2.0399, -1.2899,  0.7478,  1.4689, -1.2352],
         [-0.3336,  0.5466,  1.0611, -0.8343, -0.3241]],

        [[-1.1467,  1.1880,  1.2328,  0.6938, -1.2643],
         [-2.9654, -5.4339,  2.0389, -1.4294,  0.9106],
         [-1.1729,  1.0340,  0.6531,  0.7732, -2.1821]],

        [[ 0.7773,  0.2123, -0.5464, -0.7696,  1.1562],
         [ 0.2524,  1.9962, -0.8638,  1.9045,  0.0955],
         [-2.2084, -3.0097,  1.8324,  0.0296, -1.2678]],

        [[-0.3516, -2.9943,  2.2078, -1.1990,  1.2413],
         [ 0.3316, -1.1093, -2.3101,  0.6280,  0.4232],
         [ 0.4801,  0.1002,  0.5176, -0.3648,  0.2836]],

        [[ 2.1923,  2.3400, -0.6794,  0.9830,  0.4800],
         [ 2.4723,  1.4585,  2.8229,  2.6509,  0.5795],
         [ 0.4222, -0.1089, -1.4181, -0.7412, -0.7366]],

        [[ 0.7513,  0.2763,  0.5596,  1.1950,  0.4925],
         [-6.9139, -2.2331, -0.4577, -3.1147, -2.8759],
         [ 0.3033, -1.6810,  0.6195, -

In [63]:
x17 = torch.randn(2,2)
x18 = torch.randn(2,2)
torch.dot(x17.view(-1), x18.view(-1)), x17, x18

(tensor(1.6870), tensor([[-0.6147,  1.0675],
         [-0.2336,  0.8837]]), tensor([[-1.1205,  1.0734],
         [-1.1730, -0.4771]]))