In [2]:
import torch
import numpy as np

In [3]:
torch.__version__

'1.1.0'

In [5]:
arr = np.array([1,2,3,4,5])

In [6]:
x = torch.from_numpy(arr)
print(x)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)


In [7]:
arr2d = np.arange(0.,12.).reshape(4,3)

In [8]:
x2 = torch.from_numpy(arr2d)
print(x2)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)


In [9]:
arr = np.arange(0,5)
t = torch.from_numpy(arr)
print(t)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


In [10]:
arr[0] = 77
print(t)

tensor([77,  1,  2,  3,  4], dtype=torch.int32)


In [11]:
arr = np.arange(0,5)
t = torch.tensor(arr)
print(t)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


In [12]:
arr[0] = 77
print(arr)
print(t)

[77  1  2  3  4]
tensor([0, 1, 2, 3, 4], dtype=torch.int32)


In [13]:
#Class Constructors 

In [14]:
data = np.array([1,2,3])

In [15]:
a = torch.Tensor(data)
print(a,a.dtype)

tensor([1., 2., 3.]) torch.float32


In [16]:
b = torch.tensor(data)
print(b,b.dtype)

tensor([1, 2, 3], dtype=torch.int32) torch.int32


In [18]:
c = torch.tensor(data, dtype = torch.float)
print(c, c.dtype)

tensor([1., 2., 3.]) torch.float32


In [19]:
x = torch.empty(4,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [20]:
x = torch.zeros(4,3,dtype=torch.int64)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [21]:
x = torch.arange(0,18,2).reshape(3,3)
print(x)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])


In [22]:
x = torch.linspace(0,18,12).reshape(4,3)
print(x)

tensor([[ 0.0000,  1.6364,  3.2727],
        [ 4.9091,  6.5455,  8.1818],
        [ 9.8182, 11.4545, 13.0909],
        [14.7273, 16.3636, 18.0000]])


In [28]:
print('Old', x.type())
x = x.type(torch.int32)
print('New', x.type())

Old torch.DoubleTensor
New torch.IntTensor


In [29]:
x = torch.rand(4,3)
print(x)

tensor([[0.9751, 0.1559, 0.7443],
        [0.9912, 0.3720, 0.9737],
        [0.3767, 0.0911, 0.4973],
        [0.5528, 0.3002, 0.9427]])


In [30]:
x = torch.randn(4,3)
print(x)

tensor([[ 1.3010, -0.3751,  0.2646],
        [-1.3346, -0.0080,  0.0923],
        [ 0.6828,  1.1529,  0.2140],
        [-0.0314, -1.2256, -1.0874]])


In [32]:
x = torch.randint(0,5,(4,3))
print(x)

tensor([[3, 4, 4],
        [4, 3, 0],
        [4, 3, 3],
        [3, 2, 3]])


In [33]:
x = torch.zeros(2,5)
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [34]:
y = torch.randn_like(x)
print(y)

tensor([[ 0.3302,  0.0892,  0.9803,  0.3104,  0.1568],
        [-0.3506, -2.9658,  0.2245, -0.0726, -0.5496]])


In [35]:
z = torch.ones_like(y)
print(z)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [36]:
torch.manual_seed(42)
x = torch.rand(2,3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [37]:
torch.manual_seed(42)
x = torch.rand(2,3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


# Indexing and slicing 

In [38]:
x = torch.arange(6).reshape(3,2)
print(x)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [39]:
x[:,1]

tensor([1, 3, 5])

In [40]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

# Reshape tensor with .view( )

In [41]:
x = torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [42]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [43]:
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [44]:
x.view(5,2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

### Views reflect the most current data

In [45]:
z = x.view(2,5)
x[0]=234
print(z)

tensor([[234,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])


In [46]:
z.view(2,-1)

tensor([[234,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [49]:
z.view(5,-1)

tensor([[234,   1],
        [  2,   3],
        [  4,   5],
        [  6,   7],
        [  8,   9]])

### Adopt another tensor's shape with .view_as()

In [50]:
x.view_as(z)

tensor([[234,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

## Tensor Arithmetic

In [51]:
a = torch.Tensor([1,2,3])
b = torch.Tensor([4,5,6])
print(a + b)

tensor([5., 7., 9.])


In [52]:
print(torch.add(a,b))

tensor([5., 7., 9.])


In [55]:
result = torch.empty(3)
torch.add(a, b, out=result)
print(result)

tensor([5., 7., 9.])


In [56]:
a.add_(b)
print(a)

tensor([5., 7., 9.])


## Dot products

In [59]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
print(a.mul(b))
print(a.dot(b))

tensor([ 4, 10, 18])
tensor(32)


## Matrix multiplication

In [62]:
a = torch.Tensor([[0,2,4],[1,3,5]])
b = torch.Tensor([[6,7],[8,9],[10,11]])

print('a: ',a.size())
print('b: ',b.size())
print('a x b: ',torch.mm(a,b).size())

a:  torch.Size([2, 3])
b:  torch.Size([3, 2])
a x b:  torch.Size([2, 2])


In [63]:
print(torch.mm(a,b))

tensor([[56., 62.],
        [80., 89.]])


In [64]:
print(a.mm(b))
print(a @ b)

tensor([[56., 62.],
        [80., 89.]])
tensor([[56., 62.],
        [80., 89.]])


## Matrix multiplication with broadcasting

In [65]:
t1 = torch.randn(2, 3, 4)
t2 = torch.randn(4, 5)

In [66]:
t1

tensor([[[-0.0431, -1.6047,  1.7878, -0.4780],
         [-0.2429, -0.9342, -0.2483, -1.2082],
         [-2.3169, -0.2168, -1.3847, -0.8712]],

        [[-0.2234,  1.7174,  0.3189, -0.4245],
         [-0.8286,  0.3309, -1.5576,  0.9956],
         [-0.8798, -0.6011, -1.2742,  2.1228]]])

In [67]:
t2

tensor([[-1.0892, -0.3553, -0.9138, -0.6581,  2.2181],
        [ 0.5232,  0.3466, -0.1973, -1.0546,  1.2780],
        [ 0.1453,  0.2311,  0.0566,  0.4263,  0.5750],
        [-0.6417, -2.2064, -0.7508,  2.8140,  0.3598]])

In [68]:
print(torch.matmul(t1, t2).size())

torch.Size([2, 3, 5])


In [69]:
print(torch.matmul(t1, t2))

tensor([[[-0.2260,  0.9269,  0.8162,  1.1375, -1.2903],
         [ 0.5151,  2.3709,  1.2993, -2.3608, -2.3100],
         [ 2.7680,  2.3504,  2.7358, -1.2885, -6.5258]],

        [[ 1.4605,  1.6850,  0.2020, -2.7228,  1.7300],
         [ 0.2103, -2.1476, -0.1439,  2.3341, -1.9523],
         [-0.9037, -4.8739, -0.7433,  6.6434, -2.6886]]])


## Advanced Operations 

In [70]:
x = torch.tensor([2.,5.,8.,14.])
x.norm()

tensor(17.)

In [71]:
x = torch.ones(3,7)
x.numel()

21