In [1]:
import torch
from torch.autograd import Variable

In [2]:
tensor = torch.rand(2,2)
x = Variable(tensor, requires_grad=True)
tensor,x

(tensor([[0.5060, 0.5995],
         [0.7210, 0.9204]]), tensor([[0.5060, 0.5995],
         [0.7210, 0.9204]], requires_grad=True))

In [3]:
x.sum(), x.sqrt(), x**2, x

(tensor(2.7469, grad_fn=<SumBackward0>), tensor([[0.7113, 0.7743],
         [0.8491, 0.9594]], grad_fn=<SqrtBackward>), tensor([[0.2560, 0.3595],
         [0.5198, 0.8471]], grad_fn=<PowBackward0>), tensor([[0.5060, 0.5995],
         [0.7210, 0.9204]], requires_grad=True))

In [4]:
x.data

tensor([[0.5060, 0.5995],
        [0.7210, 0.9204]])

In [5]:
x.requires_grad, x.grad, x.grad_fn, x.volatile

C:\Users\90553\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: volatile was removed (Variable.volatile is always False)
  """Entry point for launching an IPython kernel.


(True, None, None, False)

In [6]:
x = Variable(torch.FloatTensor([3]), requires_grad=True)
y=x**3+3
z = Variable(torch.FloatTensor([5]))
x.requires_grad, y.requires_grad, z.requires_grad, y

(True, True, False, tensor([30.], grad_fn=<AddBackward0>))

In [7]:
y.grad_fn.next_functions[0][0]

In [9]:
x.grad

In [10]:
y.backward()

In [11]:
x.grad

tensor([27.])

In [12]:
x,x.grad

(tensor([3.], requires_grad=True), tensor([27.]))

In [13]:
x1 = Variable(torch.ones(2), requires_grad=True)
x2 = Variable(torch.ones(2))

In [14]:
y = x1 * 2 + x2
y

tensor([3., 3.], grad_fn=<AddBackward0>)

In [15]:
y.requires_grad

True

In [16]:
y.backward(torch.Tensor([1,1]))

In [17]:
x1.grad

tensor([2., 2.])

In [18]:
x2.grad